### ISSUE TITLE
AssertionError at /var/task/sandbox.js:198:11792

### ISSUE THREAD

**Issue by am-abudu** [ardnt/vercel-python-wsgi#10]
I got an error when I was using it.
[18:15:53.609] ====> Preparing lambda bundle
[18:16:01.226] Done!
[18:16:01.241] AssertionError [ERR_ASSERTION]: false == true
[18:16:01.241] at lae (/var/task/sandbox.js:198:11792)
[18:16:01.242] at runMicrotasks ()
[18:16:01.242] at processTicksAndRejections (internal/process/task_queues.js:95:5)
[18:16:01.242] at async n6t (/var/task/sandbox.js:220:4816)
[18:16:01.242] at async s6t (/var/task/sandbox.js:220:4356) {
[18:16:01.242] generatedMessage: true,
[18:16:01.242] code: 'ERR_ASSERTION',
[18:16:01.243] actual: false,
[18:16:01.243] expected: true,
[18:16:01.243] operator: '=='
[18:16:01.243] }
[18:16:02.863] Build completed. Populating build cache...
[18:16:02.943] Uploading build cache [11.00 B]...
[18:16:03.309] Build cache uploaded: 365.41ms

**Comment by am-abudu** [comment]
I use @vercel/python instead

**Comment by NatanFS** [comment]
Did you find any solution for this problem?

**Comment by am-abudu** [comment]
> Did you find any solution for this problem?

No, I just use official builder instead.

**Comment by NatanFS** [comment]
> > Did you find any solution for this problem?
> 
> No, I just use official builder instead.

Thanks, it worked for me. I was getting an error because I needed to change the variable name "application" to "app" in wsgi.py

**Comment by jayhale** [comment]
@NatanFS you can configure the name of the application object with the `wsgiApplicationName` option - see the readme here: https://github.com/ardnt/vercel-python-wsgi#wsgiapplicationname
